travis:
  secure:
    BINSTAR_TOKEN: B4CaPcYxb7WjjBbqAKvGgeRMKVpzw/rOPLLGuqNMGac/HtAn6K6SN/aXiYgpBoxOuLK34jhZhQMqk1MobgGYCcqySSqVQXUroyT7EBYCqCENQB/o8k8ex0a2L2LEZrr59wuIxmmoh4ujo8RQj76mYsfIbYctlRa6T6HmKfdYRCh9pXuVQcPUoejRJHQTQQzr6Tq/W8mYJddgC6LnNCBchpC45rdSd6ogxNGllXwRllCN8WWkaSlhLAca5KbmMnxt1Q4o9SQ/ys8LFP61uQEvwubuczZVbt46dLHIyrh+vvpldR9sEoaWdIYySWlov4Pc+3p6yKbaFhDY4mETUCQH7mgl2h1gAMOSgMeP6eR+mk/GgVx5D2LNpGqpOncrM5cSRxovuvK/VpEfog5U/CX3+XOSbPiZUEPzEGsMRW6SfDCWAc2BM72xXpQnPRbRIeZ3ofGfSnUO0MgfgET6PscFuP1ko2HdILLjONAl3nBa1cjrtFlfOOAK4EfQUbsNOLQMK+29LxGTcP6O1XBDIks+modqGiFZYOj8UdPrHPmYIvEthO0J5LwfquwQqWOKAf7oEhq+VwlSoYBBBVKevFWuL/vtiLajyzN2+JorXvEjm10Vtd2/uclvRcRMwY3+IR3n8saOxE2D0TZZtUPXqm+MAsTyoyR1v5gZ2WrjImZUeRs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
